### ISSUE TITLE
please add python 3.10/3.11/3.12 supports

### ISSUE THREAD

**Issue by l1t1** [Jedore/xgcondb#2]
now it supports up to python 3.9

**Comment by Jedore** [comment]
XUGU DB does not provide driver for 3.10 3.11 3.12, are you sure?

**Comment by l1t1** [comment]
in https://pypi.org/project/xgcondb/#files
there are only whl files up to python 3.9

**Comment by Jedore** [comment]
XUGU DB is closed source, they even don't have a pypi package for python driver for a long long time. I think the `xgcondb` repo already have reached the limit what i can ... :rofl:

**Comment by Jedore** [comment]
What ever ... Now it support 3.10 / 3.11 @l1t1

**Comment by l1t1** [comment]
thank you.
please also support aarch64 linux (the old version supports)

**Comment by Jedore** [comment]
uh，that is ok. But I didn't get arch linux driver for 3.10 3.11 3.12 .
